### ISSUE TITLE
Menu does not update

### ISSUE THREAD

**Issue by David5i6** [astares/Pharo-DesktopManager#2]
After creating some new desktops, the menu does not update.
I can swap desktop by using keyboard shortcuts but not by menu.

The first Desktop shows this:

![imagen](https://user-images.githubusercontent.com/7849541/80032106-f83a3780-84ea-11ea-94fb-d1b5cd526840.png)

Note that even the option to go to the next desktop is disabled but using the keyboard shortcut I swapped to the second dektops when I can see:

![imagen](https://user-images.githubusercontent.com/7849541/80032351-55ce8400-84eb-11ea-8714-fb72e365142e.png)

Also That wrong because there are only 2 desktops, other where deleted via "delete non-active desktops" menu option. (Perhaps an option to delete current desktop could be a cool feature).

If we use "Desktop Overview" menu option finally we get the correct list of desktops:

![imagen](https://user-images.githubusercontent.com/7849541/80032647-c675a080-84eb-11ea-9cfd-9e1304d45f5b.png)

Hope that coould be solved because IMHO this package is so cool.
Thanks !

P.S:  Usin Pharo 9 (with today date ) oer Windows 10.

**Comment by astares** [comment]
@David5i6 

It's more a problem of the Pharo MenubarMorph - not the DesktopManager package itself. It's only updating / reseting when it received a MethodAnnouncement with the <worldMenu> pragma - not when switching the desktop or when menu is opened.

There is a workaround: add the selected line into DesktopManager>>#switchToDesktop:

![image](https://user-images.githubusercontent.com/5980033/80035693-c035f300-84f0-11ea-882c-e1094991c8d4.png)

**Comment by David5i6** [comment]
Thanks !
